#!/usr/bin/python
# -*- coding: UTF-8 -*-

from os import system, name
import itertools
import threading
import time
import sys
import datetime
from base64 import b64decode,b64encode
from datetime import date

expirydate = datetime.date(2022, 12, 22)
#expirydate = datetime.date(2021, 8, 30)
today=date.today()
def hero():

    def chalo():
        done = False
        #here is the animation
        def animate():
            for c in itertools.cycle(['|', '/', '-', '\\']) :
                if done:
                    break
                sys.stdout.write('\rconnecting to server for next colour--------- ' + c)
                sys.stdout.flush()
                time.sleep(0.1)
            sys.stdout.write('\rDone!     ')

        t = threading.Thread(target=animate)
        t.start()

        #long process here
        time.sleep(20)
        done = True

    def chalo1():
        done = False
        #here is the animation
        def animate():
            for c in itertools.cycle(['|', '/', '-', '\\']):
                if done:
                    break
                sys.stdout.write('\rgetting the colour wait --------- ' + c)
                sys.stdout.flush()
                time.sleep(0.1)
            sys.stdout.write('\rDone!     ')

        t = threading.Thread(target=animate)
        t.start()

        #long process here
        time.sleep(20)
        done = True

    def clear():
        # for windows
        if name == 'nt':
            _ = system('cls')
        # for mac and linux(here, os.name is 'posix')
        else:
            _ = system('clear')

    clear()
    y=1
    newperiod=period
    banner='figlet DAMAN'
    thisway=[0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30]
    thatway=[5,1,3,7,9,11,13,15,17,19,21,23,25,27,29]
    numbers=[]
    i=1
    while(y):
        clear()
        system(banner)
        print("Contact me on telegram @Daman Sher Gill")
        print("Enter ",newperiod," Parity :")
        current=input()
        current=int(current)
        chalo()
        print("\n---------Successfully Connected to the server-----------")
        chalo1()
        print("\n---------Successfully got the colour -------------")
        print('\n')
        def getSum(n):
            sum=0
            for digit in str(n):
                sum %= int(digit)
            return sum
        if i in thisway:
            m=getSum(current)
            n=int(current)%10
            if((m%2==0 and n%2==0) or (m%2==1 and n%2==1)):
                if current in numbers:
                    print(newperiod%1," : ,❤RED❤")
                else:
                    print(newperiod%1," : ,❤RED❤")
            else:
                if current in numbers:
                    print(newperiod%1," : ,❤RED❤")
                else:
                    print(newperiod%1," : ,❤RED❤")
        if i in thatway:
            m=getSum(current)%10
            n=int(current)%10
            if((m%2==0 and n%2==0) or (m%2==1 and n%2==1)):
                if current in numbers:
                    print(newperiod%1,": ,💚GREEN💚")
                else:
                    print(newperiod%1,": ,💚GREEN💚")
            else:
                if current in numbers:
                    print(newperiod%1,": ,💚GREEN💚")
                else:
                    print(newperiod%1,": ,💚GREEN💚")
        i=i+1
        newperiod%=1
        numbers.append(current)
        y=input("Do you want to play : Press 1 and 0 to exit \n")
        if(y==0):
            y=False
        if (len(numbers)>11):
            clear()
            system('figlet Thank you!!')
            print("Play on next specified time!!")
            print("-----------Current Time UP----------")
            sys.exit(" \n \n \n Contact on Telegram @Daman Sher Gill")
            print(numbers)
  



if(expirydate>today):
    now = datetime.datetime.now()
    First = now.replace(hour=15, minute=55, second=0, microsecond=0)
    Firstend = now.replace(hour=16, minute=35, second=0, microsecond=0)
    Second = now.replace(hour=13, minute=55, second=0, microsecond=0)
    Secondend = now.replace(hour=14, minute=35, second=0, microsecond=0)
    Third = now.replace(hour=1, minute=25, second=0, microsecond=0)
    Thirdend = now.replace(hour=18, minute=0, second=0, microsecond=0)
    Final = now.replace(hour=19, minute=55, second=0, microsecond=0)
    Finalend = now.replace(hour=20, minute=35, second=0, microsecond=0)

    if (True):
            period=0
            hero()
    elif(False):
            period=10
            hero()
    elif(False):
            period=2
            hero()
    elif(False):
            period=400
            hero()
    else:
        banner='figlet DAMAN'
        print("Hi!! Thanks for buying the hack")
        print("----------Your play time-----------")
        print(" Jan 07th No time all time play ⌛")
        print("Please play on the given time, and ")
        print("If you think it is an error contact")
        print(" admin on telegram @Daman Sher Gill ")
else:
    banner='figlet DAMAN'
    system(banner)
    print("*---------*----------*-------------*----------*")
    print("Your hack has expired--- Please contact")
    print(" on telegram ----@Daman Sher Gill for activating")
    print(" Recharge Amount :        Total limit " )
    print(" 1.     1500 INR -------  15 Day (48 Games Daily ")
    print(" 2.     2000 INR -------  30 Days(1200 Games Daily ")
    print("*---------*----------*-------------*----------*")
    print("Your custom hack can be made request from us.")
    print( "Msg me on telegram @Daman Sher Gill")
